"""Add context_image and scenario_description to personality questions

Revision ID: 7b42f607336b
Revises: 
Create Date: 2025-05-13 20:56:52.788841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b42f607336b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personality_questions', sa.Column('context_image', sa.String(), nullable=True))
    op.add_column('personality_questions', sa.Column('scenario_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personality_questions', 'scenario_description')
    op.drop_column('personality_questions', 'context_image')
    # ### end Alembic commands ### 